GET http://restapi.test/topics/show/1
Accept: */*
Cache-Control: no-cache
Authorization: key=AAAAV-VAFJg:APA91bGcvvfbXFMuDvP-QxafH35cFt5AvZzXTh1AVflW84T48_U_07NAMZ0HqtMlPbcIoLL4DnycWKNbh_t2CWAerPdRLYBJz_up9CejHBuid3elQ7enPh_F274K8ROirchIh8031r_

###